### ISSUE TITLE
TWS version 952 is not installed

### ISSUE THREAD

**Issue by acegilz** [ib-ruby/ib-ruby#117]
Hello.

I don't know how to install it, can you please tell me how do I install the command line version of IB Gateway?

I installed this https://www.interactivebrokers.com/en/index.php?f=16457 but it's the gui version. how can I install this on my centos server?

**Comment by topofocus** [comment]
First of all, ib-gateway and ib-ruby are working with the TWS-version 952.

For a headless start look here:  Headless IBControllerGatewayStart issue in ib-controller 
https://github.com/ib-controller/ib-controller/issues/55
