### ISSUE TITLE
Next valid order id doesn't increase

### ISSUE THREAD

**Issue by JothamB** [ib-ruby/ib-ruby#139]
Whenever I place a new order with place_order the local id is 1.
Shouldn't the order id increase every time I place a new order ? How can I track and modify orders if all the orders have the same id ?

**Comment by topofocus** [comment]
Hi,
do you use a random client_id? 
You can always fetch the actual order_id by 
```ruby
 IB::Connection.current.send_message :RequestIds
```
Then »got next valid order id {nn}« is returned and stored in the log (ib-gateway console). 
It is robust and (to my knowledge) stored separately  for every client-id

**Comment by JothamB** [comment]
Thank you topofocus.
Apparently the local_id does increase but only for a single session. When the connection ends and a new connection is made the next valid order id goes back to 1.
Is there a way to make the order id consistent between sessions ?

**Comment by topofocus** [comment]
How do you establish connection?

Do you specify your client_id or do you let ib-ruby choose it?

The NextOrderId is managed by the TWS, we just fetch it from the 
application.  Thus, its important, how you connect to the tws.

If you run the provided example »place_order« *(ONLY ON A DEMO 
ACCOUNT)*, the OrderId must increase  upon each run. Otherwise please 
check our tws-settings.

Am 11.10.19 um 01:18 schrieb JothamB:

**Comment by topofocus** [comment]
There is a similar discussion in the tws-mailing-list
https://groups.io/g/twsapi/topic/34491823

**Comment by JothamB** [comment]
The link looks helpful. Unfortunately for some reason I only get the first page and cant browse to the next pages to read more information.

This is how I establish a connection: 
IB::Connection.new(:port => 7497)

I don't know what client_id is. Maybe this is my problem. How do I connect to TWS with a specific client_id ?

**Comment by topofocus** [comment]
Compile the documentation,  search for IB::Connection; the constructor is displayed as
```
new(host: '127.0.0.1', port: '4001', connect: true, reader: true, received: true, logger: default_logger, client_id: random_id, client_version: IB::Messages::CLIENT_VERSION, server_version: IB::Messages::SERVER_VERSION, **any_other_parameters_which_are_ignored) 
```
You are only specifying the port. 
`client_id` is set to `random_id`, a number between 1 and 9999. 

Just set it to a proper value. 

Take a look at the examples and/or use bin/console.rb t / bin/gateway.rb t

**Comment by JothamB** [comment]
Thank you topofocus. That was what I neeed.
