### ISSUE TITLE
Discuss the BigDecimal vs Floating Point issue

### ISSUE THREAD

**Issue by ricpruss** [ib-ruby/ib-ruby#6]
Folks seem to be having a discussion in the code.  Entering this issue so we could have a thread on the topic.
From socket.rb
"
      # Floating-point numbers shouldn't be used to store money...
      # ...but BigDecimals are too unwieldy to use in this case... maybe later
"

**Comment by topofocus** [comment]
Closed because ruby 2.x solved it for us
