### ISSUE TITLE
puts Contract.last - undefined method `relation'

### ISSUE THREAD

**Issue by enflout** [ib-ruby/ib-ruby#83]
Hi all!

1.9.3p194 :006 > c = IB::Contract.last

  IB::Contract Load (1.0ms)  SELECT "ib_contracts".\* FROM "ib_contracts" ORDER BY "ib_contracts"."id" DESC LIMIT 1

IB::Contract id: 6, con_id: 55555555, sec_type: "FOP", strike: 1700.0, currency: "USD", sec_id_type: nil, sec_id: nil, legs_description: nil, symbol: "GC", local_symbol: "OGG4 C1700", multiplier: 100, expiry: "20140530", exchange: "SMART", primary_exchange: "NYMEX", include_expired: false, right: "C", type: nil, created_at: "2013-09-01 05:00:06", updated_at: "2013-09-01 05:00:06"

1.9.3p194 :007 > puts c
NoMethodError: undefined method `relation' for #<IB::Contract:0x007f8993481bf0>
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/activemodel-3.2.14/lib/active_model/attribute_methods.rb:407:in`method_missing'
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.14/lib/active_record/attribute_methods.rb:149:in `method_missing'
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/ib-ruby-0.9.2/lib/models/ib/contract.rb:223:in`block in to_s'
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/ib-ruby-0.9.2/lib/models/ib/contract.rb:222:in `map'
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/ib-ruby-0.9.2/lib/models/ib/contract.rb:222:in`to_s'
    from (irb):7:in `puts'
    from (irb):7:in`puts'
    from (irb):7
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.14/lib/rails/commands/console.rb:47:in `start'
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.14/lib/rails/commands/console.rb:8:in`start'
    from /Users/user/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.14/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Where is my mistake?

ib-ruby: 0.9.2
TWS: 939

**Comment by topofocus** [comment]
2.5.0 :018 > oo.contract
 => #<IB::Bag:0x00000000032cb548 @attributes={"con_id"=>28812380, "symbol"=>"IECombo", "sec_type"=>"BAG", "expiry"=>"", "strike"=>0.0, "right"=>"", "multiplier"=>0, "exchange"=>"SMART", "currency"=>"USD", "local_symbol"=>"28812380", "trading_class"=>"COMB", "legs_description"=>"0", "created_at"=>2018-01-23 18:05:51 +0100, "updated_at"=>2018-01-23 18:05:51 +0100, "include_expired"=>false}, @combo_legs=[], @underlying=nil> 
2.5.0 :019 > oo.contract.sec_type
 => :bag 
2.5.0 :024 > oo.contract.to_s
 => "<Contract:  @attributes={\"con_id\"=>28812380, \"symbol\"=>\"IECombo\", \"sec_type\"=>\"BAG\", \"expiry\"=>\"\", \"strike\"=>0.0, \"right\"=>\"\", \"multiplier\"=>0, \"exchange\"=>\"SMART\", \"currency\"=>\"USD\", \"local_symbol\"=>\"28812380\", \"trading_class\"=>\"COMB\", \"legs_description\"=>\"0\", \"created_at\"=>2018-01-23 18:05:51 +0100, \"updated_at\"=>2018-01-23 18:05:51 +0100, \"include_expired\"=>false} (ActiveSupport::HashWithIndifferentAccess)  >" 

works as expected in development branch
